import { GoogleGenerativeAI } from '@google/generative-ai';
import { AIProvider, AIProviderConfig } from './interface';
import { CodeChanges, TaskContext, LogAnalysis } from '../../types';
import { JsonParsingContext } from './json-parser';
import { CodeChangesValidator } from './code-changes-validator';
import { GenericSessionManager } from './generic-session-manager';
import { Session, SessionContext } from './session-manager';
import { logger } from '../../core/utils/logger';

export class GeminiProvider implements AIProvider {
  public name = 'gemini';
  private client: GoogleGenerativeAI;
  private model: any;
  private lastTokens: { input?: number; output?: number } = {};
  private sessionManager: GenericSessionManager | null = null;

  // Model pricing per 1M tokens (input, output)
  private static readonly PRICING: Record<string, { input: number; output: number }> = {
    'gemini-2.0-flash': { input: 0.1, output: 0.4 },
    'gemini-1.5-pro': { input: 1.25, output: 5.0 },
    'gemini-1.5-flash': { input: 0.075, output: 0.3 },
  };

  constructor(private config: AIProviderConfig) {
    if (!config.apiKey) {
      throw new Error('Google AI API key is required');
    }
    this.client = new GoogleGenerativeAI(config.apiKey);
    this.model = this.client.getGenerativeModel({ model: config.model });

    // Initialize session manager if enabled
    const sessionConfig = (config as any).sessionManagement;
    if (sessionConfig?.enabled !== false) {
      this.sessionManager = new GenericSessionManager({
        providerName: 'gemini',
        maxSessionAge: sessionConfig?.maxSessionAge,
        maxHistoryItems: sessionConfig?.maxHistoryItems,
        enabled: sessionConfig?.enabled,
      });
      logger.debug('[GeminiProvider] Session management initialized');
    }
  }

  /**
   * Get last token usage from the most recent API call
   * Note: Gemini provides token counts via usageMetadata
   */
  public getLastTokens(): { input?: number; output?: number } {
    return { ...this.lastTokens };
  }

  /**
   * Get session by ID
   */
  getSession(sessionId: string): Session | null {
    return this.sessionManager?.getSession(sessionId) || null;
  }

  /**
   * Get or create session for a given context
   */
  getOrCreateSession(context: SessionContext): Session | null {
    return this.sessionManager?.getOrCreateSession(context) || null;
  }

  /**
   * Check if provider supports sessions
   */
  supportsSessions(): boolean {
    return this.sessionManager !== null;
  }

  /**
   * Calculate cost in USD for token usage (provider-native pricing)
   */
  calculateCost(tokens: { input?: number; output?: number }): number {
    const pricing = GeminiProvider.PRICING[this.config.model] || { input: 10.0, output: 10.0 };
    const inputCost = ((tokens.input || 0) / 1_000_000) * pricing.input;
    const outputCost = ((tokens.output || 0) / 1_000_000) * pricing.output;
    return inputCost + outputCost;
  }

  async generateCode(prompt: string, context: TaskContext): Promise<CodeChanges> {
    const systemPrompt = `You are an expert software developer. Generate code changes based on the task description.
Include both feature implementation and test code together. Return your response as a JSON object with this structure:
{
  "files": [
    {
      "path": "relative/path/to/file",
      "content": "file content here",
      "operation": "create" | "update" | "delete"
    }
  ],
  "summary": "Brief summary of changes"
}`;

    const userPrompt = `Task: ${context.task.title}
Description: ${context.task.description}

${context.codebaseContext ? `Codebase Context:\n${context.codebaseContext}\n` : ''}

${prompt}`;

    try {
      const result = await this.model.generateContent(`${systemPrompt}\n\n${userPrompt}`);
      const response = result.response;
      const text = response.text();

      // Track token usage if available from usageMetadata
      if (response.usageMetadata) {
        this.lastTokens = {
          input: response.usageMetadata.promptTokenCount,
          output: response.usageMetadata.candidatesTokenCount,
        };
      }

      // Use shared JSON parser for consistent extraction
      const parsingContext: JsonParsingContext = {
        providerName: 'gemini',
        taskId: context.task.id,
        prdId: context.prdId,
        phaseId: context.phaseId ?? undefined,
      };
      const validationResult = CodeChangesValidator.validate(text, parsingContext);
      if (validationResult.valid && validationResult.codeChanges) {
        return validationResult.codeChanges;
      }

      // Fallback: create a single file
      return {
        files: [
          {
            path: 'generated-code.ts',
            content: text,
            operation: 'create' as const,
          },
        ],
        summary: 'Code generated by Google Gemini',
      };
    } catch (error) {
      throw new Error(`Gemini API error: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Generate text without expecting JSON CodeChanges format
   * Used for PRD building (schemas, test plans, etc.) where plain text output is expected
   */
  async generateText(prompt: string, options?: { maxTokens?: number; temperature?: number; systemPrompt?: string }): Promise<string> {
    const maxTokens = options?.maxTokens || this.config.maxTokens || 4000;
    const temperature = options?.temperature ?? 0.7;
    const systemPrompt = options?.systemPrompt || '';

    const fullPrompt = systemPrompt ? `${systemPrompt}\n\n${prompt}` : prompt;
    const result = await this.model.generateContent({
      contents: [{ role: 'user', parts: [{ text: fullPrompt }] }],
      generationConfig: { maxOutputTokens: maxTokens, temperature },
    });

    return result.response.text();
  }

  async analyzeError(error: string, context: TaskContext): Promise<LogAnalysis> {
    const prompt = `Analyze this error and provide recommendations. Return JSON:

{
  "errors": ["list of errors"],
  "warnings": ["list of warnings"],
  "summary": "brief summary",
  "recommendations": ["actionable recommendations"]
}

Error:
${error}

Task Context:
${context.task.description}`;

    try {
      const result = await this.model.generateContent(prompt);
      const text = result.response.text();

      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        try {
          return JSON.parse(jsonMatch[0]) as LogAnalysis;
        } catch {
          // Fallback
        }
      }

      return {
        errors: [error],
        warnings: [],
        summary: 'Error analysis completed',
        recommendations: ['Review the error message and fix the underlying issue'],
      };
    } catch (error) {
      return {
        errors: [error instanceof Error ? error.message : String(error)],
        warnings: [],
        summary: 'Failed to analyze error',
      };
    }
  }
}

