import { AIProvider, AIProviderConfig } from './interface';
import { CodeChanges, TaskContext, LogAnalysis } from '../../types';
import { extractCodeChanges, JsonParsingContext } from './json-parser';
import { GenericSessionManager } from './generic-session-manager';
import { Session, SessionContext } from './session-manager';
import { logger } from '../../core/utils/logger';

export class OllamaProvider implements AIProvider {
  public name = 'ollama';
  private baseUrl: string;
  private lastTokens: { input?: number; output?: number } = {};
  private sessionManager: GenericSessionManager | null = null;

  constructor(private config: AIProviderConfig) {
    this.baseUrl = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';

    // Initialize session manager if enabled
    const sessionConfig = (config as any).sessionManagement;
    if (sessionConfig?.enabled !== false) {
      this.sessionManager = new GenericSessionManager({
        providerName: 'ollama',
        maxSessionAge: sessionConfig?.maxSessionAge,
        maxHistoryItems: sessionConfig?.maxHistoryItems,
        enabled: sessionConfig?.enabled,
      });
      logger.debug('[OllamaProvider] Session management initialized');
    }
  }

  /**
   * Get last token usage from the most recent API call
   */
  public getLastTokens(): { input?: number; output?: number } {
    return { ...this.lastTokens };
  }

  /**
   * Get session by ID
   */
  getSession(sessionId: string): Session | null {
    return this.sessionManager?.getSession(sessionId) || null;
  }

  /**
   * Get or create session for a given context
   */
  getOrCreateSession(context: SessionContext): Session | null {
    return this.sessionManager?.getOrCreateSession(context) || null;
  }

  /**
   * Check if provider supports sessions
   */
  supportsSessions(): boolean {
    return this.sessionManager !== null;
  }

  async generateCode(prompt: string, context: TaskContext): Promise<CodeChanges> {
    const systemPrompt = `You are an expert software developer. Generate code changes based on the task description.
Include both feature implementation and test code together. Return your response as a JSON object with this structure:
{
  "files": [
    {
      "path": "relative/path/to/file",
      "content": "file content here",
      "operation": "create" | "update" | "delete"
    }
  ],
  "summary": "Brief summary of changes"
}`;

    const userPrompt = `Task: ${context.task.title}
Description: ${context.task.description}

${context.codebaseContext ? `Codebase Context:\n${context.codebaseContext}\n` : ''}

${prompt}`;

    try {
      const response = await fetch(`${this.baseUrl}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: this.config.model,
          prompt: `${systemPrompt}\n\n${userPrompt}`,
          stream: false,
          options: {
            temperature: this.config.temperature || 0.7,
            num_predict: this.config.maxTokens || 4000,
          },
        }),
      });

      if (!response.ok) {
        throw new Error(`Ollama API error: ${response.statusText}`);
      }

      const data = await response.json() as { 
        response?: string;
        prompt_eval_count?: number;
        eval_count?: number;
      };
      const text = data.response || '';

      // Track token usage if available
      if (data.prompt_eval_count !== undefined || data.eval_count !== undefined) {
        this.lastTokens = {
          input: data.prompt_eval_count,
          output: data.eval_count,
        };
      }

      // Use shared JSON parser for consistent extraction
      const parsingContext: JsonParsingContext = {
        providerName: 'ollama',
        taskId: context.task.id,
        prdId: context.prdId,
        phaseId: context.phaseId ?? undefined,
      };
      const codeChanges = extractCodeChanges(text, undefined, parsingContext);
      if (codeChanges) {
        return codeChanges;
      }

      // Fallback: create a single file
      return {
        files: [
          {
            path: 'generated-code.ts',
            content: text,
            operation: 'create' as const,
          },
        ],
        summary: 'Code generated by Ollama',
      };
    } catch (error) {
      throw new Error(`Ollama API error: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  /**
   * Generate text without expecting JSON CodeChanges format
   * Used for PRD building (schemas, test plans, etc.) where plain text output is expected
   */
  async generateText(prompt: string, options?: { maxTokens?: number; temperature?: number; systemPrompt?: string }): Promise<string> {
    const maxTokens = options?.maxTokens || this.config.maxTokens || 4000;
    const temperature = options?.temperature ?? 0.7;
    const systemPrompt = options?.systemPrompt || '';

    const fullPrompt = systemPrompt ? `${systemPrompt}\n\n${prompt}` : prompt;

    const response = await fetch(`${this.baseUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: this.config.model,
        prompt: fullPrompt,
        stream: false,
        options: { temperature, num_predict: maxTokens },
      }),
    });

    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.statusText}`);
    }

    const data = await response.json() as { response?: string };
    return data.response || '';
  }

  async analyzeError(error: string, context: TaskContext): Promise<LogAnalysis> {
    const prompt = `Analyze this error and provide recommendations. Return JSON:

{
  "errors": ["list of errors"],
  "warnings": ["list of warnings"],
  "summary": "brief summary",
  "recommendations": ["actionable recommendations"]
}

Error:
${error}

Task Context:
${context.task.description}`;

    try {
      const response = await fetch(`${this.baseUrl}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: this.config.model,
          prompt: prompt,
          stream: false,
          options: {
            temperature: 0.3,
            num_predict: 2000,
          },
        }),
      });

      if (!response.ok) {
        throw new Error(`Ollama API error: ${response.statusText}`);
      }

      const data = await response.json() as { response?: string };
      const text = data.response || '';

      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        try {
          return JSON.parse(jsonMatch[0]) as LogAnalysis;
        } catch {
          // Fallback
        }
      }

      return {
        errors: [error],
        warnings: [],
        summary: 'Error analysis completed',
        recommendations: ['Review the error message and fix the underlying issue'],
      };
    } catch (error) {
      return {
        errors: [error instanceof Error ? error.message : String(error)],
        warnings: [],
        summary: 'Failed to analyze error',
      };
    }
  }
}

